name: Deploy function app

on: workflow_dispatch

jobs:
  deploy_function_app:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Logon to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep file
        shell: bash
        env:
          ALLOWED_IP_ADDRESSES: ${{ vars.ALLOWED_IP_ADDRESSES }}
          AZURE_LOCATION: eastus
          ACTION_ON_UNMANAGE: deleteAll
          DEPLOYMENT_STACK_NAME: ${{ vars.DEPLOYMENT_STACK_NAME }}
          TEMPLATE_FILE_PATH: "${{ github.workspace }}/bicep/main.bicep"
          TEMPLATE_PARAMETER_FILE_PATH: "${{ github.workspace }}/bicep/main.bicepparam"
        run: |
          set -euo pipefail

          echo "Creating deployment stack..."
          az stack sub create \
            --action-on-unmanage "$ACTION_ON_UNMANAGE" \
            --deny-settings-mode none \
            --location "$AZURE_LOCATION" \
            --name "$DEPLOYMENT_STACK_NAME" \
            --template-file "$TEMPLATE_FILE_PATH" \
            --parameters "$TEMPLATE_PARAMETER_FILE_PATH" \
            --yes
      - name: Publish function app
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          DEPLOYMENT_STACK_NAME: ${{ vars.DEPLOYMENT_STACK_NAME }}
          ZIP_FILE_PATH: ${{ runner.temp }}/function-app.zip
        run: |
          set -euo pipefail

          echo "Creating zip file..."
          zip -r "$ZIP_FILE_PATH" \
            "${{ github.workspace }}/src/functionapp" \
            -i '*functionapp/function_app.py' \
            -i '*functionapp/host.json' \
            -i '*functionapp/requirements.txt' \
            -i '*functionapp/import_on_timer.py' \
            -i '*functionapp/import_with_service_bus.py'

          echo "Giving network access to storage account..."
          PUBLIC_IP_ADDRESS=$(curl ipinfo.io/ip)
          DEPLOYMENT_STACK=$(az stack sub show -n "$DEPLOYMENT_STACK_NAME")
          RESOURCE_GROUP_NAME=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.resourceGroupName.value')
          STORAGE_ACCOUNT_NAME=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.storageAccountName.value')
          az storage account network-rule add \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --ip-address "$PUBLIC_IP_ADDRESS" \
            --action Allow

          echo "Giving permissions to deploy to the storage container..."
          STORAGE_ACCOUNT_CONTAINER_RESOURCE_ID=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.storageAccountContainerResourceId.value')
          az role assignment create \
            --role "Storage Blob Data Contributor" \
            --assignee "$AZURE_CLIENT_ID" \
            --scope "$STORAGE_ACCOUNT_CONTAINER_RESOURCE_ID"
          sleep 120

          echo "Publishing function app..."
          FUNCTION_APP_NAME=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.functionAppName.value')
          az functionapp deployment source config-zip \
            --name "$FUNCTION_APP_NAME" \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --src "$ZIP_FILE_PATH"

          echo "Removing network access..."
          az storage account network-rule remove \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --ip-address "$PUBLIC_IP_ADDRESS"
